### ISSUE TITLE
タイトルとバージョンが

### ISSUE THREAD

**Issue by pen-ozi** [hiroto-guruguru/hiroto-guruguru.github.io#1]
![スクリーンショット 2024-11-01 175928](https://github.com/user-attachments/assets/7027bc79-b76f-4d3d-924f-b59b46362b1d)
![スクリーンショット 2024-11-01 175933](https://github.com/user-attachments/assets/d86b2343-96a6-4dd7-98c3-e55e31106fa1)

ベータなのかアルファなのか
どちらかにそろえたほうがいいかも

**Comment by hiroto-guruguru** [comment]
OK
